### ISSUE TITLE
add possibility to delete (hide?) dealers

### ISSUE THREAD

**Issue by egon0** [MateMonkey/frontend#13]
some of the imported dealers in my area are closed, maybe a flag for "dealer not available anymore" would help. if the dealer is flagged "closed" one could say: "this information is correct", if a threshold - maybe 5 confirmations is reached, the dealer is deleted permanently (or hidden).

**Comment by mguentner** [comment]
The current policy is to send me these links via twitter/email, I will then delete the dealer by hand :)
For now everything else is overengineering :)
