### ISSUE TITLE
Add geolocation getCurrentPosition / current map location onLoad

### ISSUE THREAD

**Issue by CodeBrauer** [MateMonkey/frontend#21]
enhancement idea:

``` js
navigator.geolocation.getCurrentPosition(onSuccess, onError);

function onSuccess(position) {
  console.log(position.coords.latitude, position.coords.longitude);
}
```

So you have an onLoad event for this and center the map to the current position. That would be awesome

**Comment by CodeBrauer** [comment]
related to #10

**Comment by mguentner** [comment]
Sure. If you want, you can fork the project and create a PR! :muscle:

**Comment by CodeBrauer** [comment]
This seems to be already implemented.
