### ISSUE TITLE
Add MATE MATE (Thomas Henry

### ISSUE THREAD

**Issue by CodeBrauer** [MateMonkey/frontend#22]
**http://mate-mate.de**
![mate](http://www.drinks-of-the-world.de/bilder/mate_thomas_henry,p-24000129,s-600.jpg)

**Comment by mguentner** [comment]
Hi.

https://matemonkey.com/map/dealer/?@=5,47.532038,21.950684&products=37

MATE MATE 0.5l is already present.

**Comment by CodeBrauer** [comment]
Overlooked it, thanks!
