### ISSUE TITLE
no mapquest tiles anymore

### ISSUE THREAD

**Issue by egon0** [MateMonkey/frontend#23]
mapquest has disabled direct tile acces on july 11th. so at the moment we don't have any tiles.

**Comment by CodeBrauer** [comment]
Yes - read more here: http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

I think the only thing that has to be changed is the tile provider:

[/app/js/map.js#L164](https://github.com/MateMonkey/frontend/blob/4946d250daec09cc2ec9d21019b460d954b85255/app/js/map.js#L164)

```
http://{s}.tile.osm.org/{z}/{x}/{y}.png
```

Style:
![osm](http://a.tile.osm.org/16/35211/21489.png)

Switching to OSM default maps would work fine, I think.

**Comment by egon0** [comment]
you should setup a nginx-tilecache. direct usage will end in an ban.

i have a tile-cache running:

```
https:///tiles{s}.freifunk-jena.de/{z}/{x}/{y}.png
```

s = 0,1,2,3,4,5,6,7,8,9 ;)

edit: http://wiki.openstreetmap.org/wiki/Tile_usage_policy

**Comment by mguentner** [comment]
@CodeBrauer: Thanks. I will switch to MapQuest with an appkey for the moment and then try to avoid MapQuest with some other solution.
@egon0: Thanks for the offer. I will have a look :+1:

**Comment by mguentner** [comment]
Argh. MapQuest sucks. They require a Leaflet plugin and this whole angular-leaflet clusterfuck will probably break. Switched to @egon0's tile cache for now with commit 6505019f60bd48995c8de00f24dbcc1887e4163d.
